#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  {{PROJECT}} — deployment script
#  Generated by VPS Deployer. Edit freely, then use
#  "Deploy (my edits)" in the TUI to install your version.
# ═══════════════════════════════════════════════════════════════
set -euo pipefail

BRANCH="{{BRANCH}}"
ROOT="{{ROOT}}"
BACKEND_DIR="$ROOT/backend"
FRONTEND_DIR="$ROOT/frontend"
SERVICE="{{SERVICE}}"

{{BACKEND_BLOCK}}

{{FRONTEND_BLOCK}}

echo "==> Reloading nginx"
sudo systemctl reload nginx || true

echo "✅ Deploy complete"