### `templates/documentation.md.tpl`

```markdown
#  {{PROJECT}} — VPS Deployment Guide

> Auto-generated by **VPS Deployer** on {{DATE}}.
> This file is the single reference for **where everything lives** on this
> server and **how each piece works**. Regenerate anytime with the 📖 button.

| Setting | Value |
|---|---|
| Backend stack | {{STACK}} |
| Git branch | `{{BRANCH}}` |
| Backend port | `{{PORT}}` |
| Domain | {{DOMAIN}} |
| Health check | `http://127.0.0.1:{{PORT}}{{HEALTH}}` |
| Run user | `{{USER}}` |

---

## 1. Directory map — what is where

```text
{{TARGET_DIR}}/
├── backend/                 ← backend repo:  {{BE_REPO}}
├── frontend/                ← frontend repo: {{FE_REPO}}
├── deploy.sh                ← one-shot production deploy script
└── .vps-deployer/           ← staged configs (edit with vim, reinstall via TUI)
    ├── deploy.sh
    ├── {{SERVICE}}.service
    ├── {{DOMAIN_FILE}}
    ├── backup.sh
    └── DOCUMENTATION.md     ← this file

{{DB_DIR}}          ← database files
{{UPLOADS_DIR}}          ← user uploads
{{BACKUP_DIR}}          ← backup archives (backup-*.tar.gz)
```

## 2. Backend service (systemd)

The backend runs as a systemd service, which means:
- it starts automatically at boot,
- it restarts automatically if it crashes (`Restart=always`),
- logs go to the journal.

| Item | Path / value |
|---|---|
| Service name | `{{SERVICE}}` |
| Installed unit | `/etc/systemd/system/{{SERVICE}}.service` |
| Editable source | `{{STAGING}}/{{SERVICE}}.service` |
| Exec command | `{{EXEC_START}}` |
| Working dir | `{{TARGET_DIR}}/backend` |
| Env vars | `PORT={{PORT}}`, `DATABASE_PATH={{DB_DIR}}`, `UPLOADS_PATH={{UPLOADS_DIR}}` |

**Everyday commands**

```bash
sudo systemctl status {{SERVICE}}          # is it running?
sudo systemctl restart {{SERVICE}}         # restart
sudo systemctl stop {{SERVICE}}            # stop
sudo journalctl -u {{SERVICE}} -f          # follow live logs
sudo journalctl -u {{SERVICE}} --since "1 hour ago"
```

> ✏️ To change the unit: edit `{{STAGING}}/{{SERVICE}}.service`,
> then press **"Deploy (my edits)"** in the TUI — it copies the file to
> /etc/systemd/system and reloads systemd.

## 3. Frontend & nginx

| Item | Path / value |
|---|---|
| Built frontend | `{{DIST}}` |
| vhost (installed) | {{NGINX_INSTALLED}} |
| Editable source | `{{STAGING}}/{{DOMAIN_FILE}}` |
| API proxy | `{{PREFIX}}` → `http://127.0.0.1:{{PORT}}` |
| Max upload size | `{{MAX_BODY}}` |

nginx serves the built frontend and reverse-proxies `{{PREFIX}}*` to the
backend port. HTTPS is handled by certbot (Let's Encrypt):

```bash
sudo certbot renew --dry-run                       # verify auto-renewal
sudo certbot certificates                          # list certificates
sudo nginx -t && sudo systemctl reload nginx       # apply manual edits safely
```

## 4. Firewall (UFW)

Opened rules for this project: **{{UFW_RULES}}**

```bash
sudo ufw status numbered       # inspect
sudo ufw delete allow <rule>   # remove a rule
```

## 5. Deployment workflow

`{{TARGET_DIR}}/deploy.sh` is the heart of deployments. It:

1. pulls the `{{BRANCH}}` branch for backend **and** frontend,
2. builds the backend (`{{BUILD_CMD}}`),
3. builds the frontend (`npm ci && npm run build` when package.json exists),
4. restarts `{{SERVICE}}` and reloads nginx.

```bash
cd {{TARGET_DIR}} && ./deploy.sh       # manual deploy
```

TUI buttons:
- **🚀 Deploy** — regenerate staged files from the forms and install everything
- **📥 Deploy (my edits)** — install the staged files exactly as you edited them
- **⇩ Pull & Deploy** — just run deploy.sh
- **📜 Files only** — (re)create staged files without installing

## 6. Backups

| Item | Value |
|---|---|
| Script | `{{STAGING}}/backup.sh` |
| Archive dir | `{{BACKUP_DIR}}` |
| Retention | last {{RETENTION}} archives |
| Cron | {{CRON_LINE}} |

**Restore**

```bash
mkdir -p /tmp/restore
tar -xzf {{BACKUP_DIR}}/backup-<STAMP>.tar.gz -C /tmp/restore
sudo cp -a /tmp/restore/db/. {{DB_DIR}}/             # database dir
sudo cp -a /tmp/restore/uploads/. {{UPLOADS_DIR}}/   # uploads dir
sudo systemctl restart {{SERVICE}}
```

## 7. Health check & troubleshooting

```bash
curl -sS http://127.0.0.1:{{PORT}}{{HEALTH}}
```

| Symptom | First things to check |
|---|---|
| 502 Bad Gateway | `sudo systemctl status {{SERVICE}}` — backend down or wrong port |
| Site not reachable | `sudo ufw status` · nginx running? · DNS points to this VPS? |
| Certificate warning | `sudo certbot renew` |
| Build failure | run `./deploy.sh` manually to see full output |
| Service fails at boot | `sudo journalctl -u {{SERVICE}} -n 50` |

## 8. Complete uninstall

The TUI **🗑 Delete** button performs all of this:

1. `systemctl stop/disable {{SERVICE}}` + remove `/etc/systemd/system/{{SERVICE}}.service`
2. remove nginx vhost + symlink, reload nginx
3. `certbot delete --cert-name {{DOMAIN}}`
4. remove UFW rules
5. delete `{{TARGET_DIR}}`, `{{DB_DIR}}`, `{{UPLOADS_DIR}}`, `{{BACKUP_DIR}}`
6. remove the project entry from `~/.config/vps-deployer/projects/`

## 9. Cheat sheet

```bash
# service
sudo systemctl restart {{SERVICE}} && sudo journalctl -u {{SERVICE}} -f

# deploy
cd {{TARGET_DIR}} && ./deploy.sh

# backup now
bash {{STAGING}}/backup.sh

# nginx
sudo nginx -t && sudo systemctl reload nginx

# logs
sudo journalctl -u {{SERVICE}} -f
sudo tail -f /var/log/nginx/error.log
```

## 10. How the TUI maps to this server

| TUI tab | What it produces |
|---|---|
| 1·Repos | cloned `backend/` & `frontend/` dirs, branch, systemd ExecStart |
| 2·Dirs | directory layout + env vars in the unit |
| 3·Ports | PORT env, UFW rules, health endpoint |
| 4·Nginx | nginx vhost + certbot certificate |
| 5·Backup | backup.sh + cron job |
| 6·Projects | per-project JSON in `~/.config/vps-deployer/projects/` |
| 7·Review | staged files in `{{STAGING}}` + installation |

---
*Generated by VPS Deployer. Regenerated by the 📖 Get docs button —
manual edits to this file will be overwritten on regeneration.*
```